package com.monocept.chatbot.service.impl;
import com.monocept.chatbot.Entity.History;
import com.monocept.chatbot.exceptions.ResourcesNotFoundException;
import com.monocept.chatbot.model.dto.HistoryDTO;
import com.monocept.chatbot.Exception.InvalidEmailException;
import com.monocept.chatbot.reposiotry.ChatHistoryRepository;
import com.monocept.chatbot.service.ChatHistoryService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Service
public class ChatHistoryServiceImpl implements ChatHistoryService {
    private static final Logger logger = LoggerFactory.getLogger(ChatHistoryServiceImpl.class);
    private final ChatHistoryRepository chatHistoryRepository;
    private final RedisTemplate<String, Object> redisTemplate;
    private final com.monocept.chatbot.repository.RedisChatHistoryRepository redisChatHistoryRepository;

    public ChatHistoryServiceImpl(ChatHistoryRepository chatHistoryRepository, RedisTemplate<String, Object> redisTemplate, com.monocept.chatbot.repository.RedisChatHistoryRepository redisChatHistoryRepository) {
        this.chatHistoryRepository = chatHistoryRepository;
        this.redisTemplate = redisTemplate;
        this.redisChatHistoryRepository = redisChatHistoryRepository;
    }

    @Override
    @Transactional
    public Page<HistoryDTO> getMessagesFromLast90Days(String email, int page, int size) {
        if (email == null || email.isEmpty()) {
            throw new InvalidEmailException("Email is null or empty");
        }

        History newMessage = new History();
        newMessage.setMsgId(1L);  // Sample message ID, can be autogenerated by database
        newMessage.setMsg("Hello");
        newMessage.setMessageTo("user3");
        newMessage.setDateTime(LocalDateTime.now());  // Current timestamp
        newMessage.setReplyId("reply123");
        newMessage.setType("text");
        newMessage.setMediaUrl(null);  // No media in this sample
        newMessage.setActivity("Like");
        newMessage.setSsoid("SSO12345");  // Sample SSO ID
        newMessage.setAgentId("agent001");
        newMessage.setEmail("user3@example.com");
        newMessage.setSession("session001");  // Sample session ID
        storeNewMessageInRedis(email, newMessage);

        logger.info("Fetching chat history from redis for email: {}", email);
        // Get the 3-day chat history from Redis
        List<HistoryDTO> chatHistoryDetailsEmail = redisChatHistoryRepository.getChatHistoryDetailsEmail(email);
        Pageable pageable = PageRequest.of(page, size);
        Page<HistoryDTO> recentMessagesFromRedis = convertListToPage(chatHistoryDetailsEmail, pageable);
        List<HistoryDTO> finalMessages = new ArrayList<>();
        if (recentMessagesFromRedis != null && !recentMessagesFromRedis.isEmpty()) {
             finalMessages.addAll(recentMessagesFromRedis.getContent());
            logger.info("Found {} recent messages from Redis", finalMessages.size());
        }
        //  fetch the remaining messages for the next 87 days from the database
        LocalDateTime dateTime87DaysAgo = LocalDateTime.now().minusDays(87);
        Page<HistoryDTO> messagesFromDb87Days = chatHistoryRepository.findMessagesFromDayswrtEmail(dateTime87DaysAgo, email, pageable);
        if (messagesFromDb87Days.isEmpty() && finalMessages.isEmpty()) {
            logger.error("No messages found for email: {} in the last 90 days", email);
            throw new ResourcesNotFoundException("No messages found for the provided email in the last 90 days.");
        }
        // Add 87 days' data to the final list
        finalMessages.addAll(messagesFromDb87Days.getContent());
        logger.info("Found {} messages from the database for the past 87 days", messagesFromDb87Days.getContent().size());
        // Calculate total elements combined count of messages from Redis and the database
        long totalElements = finalMessages.size();
        logger.info("Total combined messages from Redis and DB: {}", totalElements);
        // Convert final list back to a Page
        return new PageImpl<>(finalMessages, pageable, totalElements);
    }

    public void storeNewMessageInRedis(String email, History newMessage) {
        // Save the new message in Redis
        logger.info("Storing new message in Redis for email: {}", email);
        redisChatHistoryRepository.saveChatHistoryDetails(email,newMessage);
        chatHistoryRepository.save(newMessage);
        // Now call an asynchronous job to move it to DB later
        moveMessageToDbAsync(newMessage);
    }

    @Async
    @Transactional
    public void moveMessageToDbAsync(History newMessage) {
        // Here you can write to the DB later.
        logger.info("Asynchronously saving message to DB: {}", newMessage);
        chatHistoryRepository.save(newMessage);
    }
    /*@Transactional
    public void moveOldMessagesToDb(String email) {
        LocalDateTime fiveMinutesBefore = LocalDateTime.now().minus(3, ChronoUnit.DAYS).minus(5, ChronoUnit.MINUTES);
        logger.info("Moving old messages to DB for email: {}", email);
        // Fetch all messages in Redis
        List<HistoryDTO> redisMessages = redisChatHistoryRepository.getChatHistoryDetailsEmail(email);
        if (redisMessages != null && !redisMessages.isEmpty()) {
            List<History> messagesToMoveToDb = redisMessages.stream()
                    .map(dto -> {
                        History message = convertToHistory(dto);
                        return message;
                    })
                    .filter(message -> message.getDateTime().isBefore(fiveMinutesBefore))
                    .collect(Collectors.toList());
            // Save 3 days older messages to the Database
            if (!messagesToMoveToDb.isEmpty()) {
                chatHistoryRepository.saveAll(messagesToMoveToDb);
                logger.info("Moved {} messages from Redis to DB", messagesToMoveToDb.size());
            } else {
                logger.info("No messages older than 3 days found in Redis to move to DB");
            }
        } else {
            logger.warn("No messages found in Redis for email: {}", email);
        }

    }*/
    private Page<HistoryDTO> convertListToPage(List<HistoryDTO> list, Pageable pageable) {
        int start = Math.min((int) pageable.getOffset(), list.size());
        int end = Math.min((start + pageable.getPageSize()), list.size());
        List<HistoryDTO> sublist = list.subList(start, end);
        return new PageImpl<>(sublist, pageable, list.size());
    }

  /*  private History convertToHistory(HistoryDTO dto) {
        History history = new History();
        history.setDateTime(dto.getDateTime());
        history.setMessageTo(dto.getMessageTo());
        // Add other necessary fields
        return history;
    }*/

}
