FROM openjdk:21-jdk-slim
EXPOSE 9090
ADD chatbot-service/target/chatbot-service-0.0.1-SNAPSHOT.jar chatbot-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/chatbot-service-0.0.1-SNAPSHOT.jar"]


#D:\Chat-Bot-App\ChatBot\chatbot-service\Dockerfile