server:
  port: 9092

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://postgres:5432/chatbot
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO

payload:
  encryption:
    key: MK234S98CLKSJRE98WEK54JFSD989SDF
    iv: 9LP300U3920Y3KK3
    type: AES/CBC/PKCS5Padding
  decryption:
    type: AES/CBC/NoPadding

redis:
  host: redis  # 🔁 use service name 'redis'
  port: 6379

mli:
  message:
    send:
      url: http://host.docker.internal:8081/api/v1/message/send
      # 🔁 If 8081 is hosted on host machine, use host.docker.internal (for Linux, see below)
