server:
  port: 9095

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://postgres:5432/chatbot
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    sql-script-encoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: INFO

payload:
  encryption:
    key: MK234S98CLKSJRE98WEK54JFSD989SDF
    iv: 9LP300U3920Y3KK3
    type: AES/CBC/PKCS5Padding
  decryption:
    type: AES/CBC/NoPadding

redis:
  host: redis
  port: 6379

mli:
  message:
    send:
      url: http://host.docker.internal:8081/api/v1/message/send
    url: https://third-party.com/webhook/message

chatbot:
  name: :Ely

socketio:
  hostname: 0.0.0.0 # ✅ Not localhost
  port: 5050
  allowed-origins: "*"
  client:
    url: http://host.docker.internal:5050


chat:
  history:
    cron: "0 7 16 * * ?" # Every day at 4:07 PM