# For the postgres
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_history_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: INFO

payload:
  encryption:
    key: MK234S98CLKSJRE98WEK54JFSD989SDF
    iv: 9LP300U3920Y3KK3
    type: AES/CBC/PKCS5Padding
  decryption:
    type: AES/CBC/NoPadding


redis:
  host: localhost
  port: 6000

mli:
  message:
    send:
      url: http://localhost:8081/api/v1/message/send



