version: '3.8'

services:
  app:
    build: .
    container_name: spring_app
    ports:
      - "9090:9090"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: always

  redis:
    image: "redis:latest"
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_gui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
